# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 359bdfaea37c7af59fb27b2f99387beaf341eb96e43d6e35847e0c6423158195ad74ee5ea09657f1b52f79c8cf08cb5f32f6030ee3ad3782a86ab43dabf0ba03

test:
  secret_key_base: c3a947f519d9981eaed0679a5e1cd60e0a4ec636035834a3b8ba17897a0344059c547f6fb48f147c6f657b61ef6a081a59fb502d76daef44d5d658fc1aa094d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
